version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: projekt-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projekt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"   # host:container (czyli 3307 na Twoim komputerze -> 3306 w kontenerze)
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: